title: Flo Edge
description: Building vision based autonomy stack for masses!
remote_theme: pmarsceill/just-the-docs

url: https://edge.flomobility.com/

aux_links:
  Buy Now: https://edge.flomobility.com/
