title: Flo Edge
description: Compute, sensor & comms platform for ai and robotics application.
remote_theme: pmarsceill/just-the-docs

url: https://edge.flomobility.com/

aux_links:
  Buy Now: https://edge.flomobility.com/
